os: linux
dist: xenial
language: shell

jobs:
  include:
    - stage: test receiver-mock
      language: rust
      rust: stable
      before_script:
        - cd src/rust/receiver-mock/
      script:
        - cargo test

    - stage: build sumologic-kubernetes-tools docker image
      language: ruby
      dist: trusty
      services: docker
      script:
        - bash ci/build.sh
      branches:
        only:
        - master
        - /^release-v\d+\.\d+$/
        - /^v\d+\.\d+\.\d+$/
        - /^v\d+\.\d+\.\d+-(alpha|beta|rc)\.\d+$/