os: linux
# Somehow focal (20.04) is available for amd64 but when
# ran on travis it falls back to xenial (16.04).
dist: bionic
arch: amd64
language: shell

jobs:
  include:
    - stage: shellcheck build.sh
      install:
        - sudo apt update
        - sudo apt install shellcheck
      script:
        - shellcheck --norc --enable all ci/build.sh

    - stage: test
      language: rust
      rust: stable
      # ref: https://docs.travis-ci.com/user/languages/rust/#dependency-management
      cache: cargo
      before_script:
        - cd src/rust/receiver-mock/
      script:
        - cargo test

    - stage: build
      language: ruby
      # TODO: upgrade this?
      dist: trusty
      services: docker
      script:
        - bash ci/build.sh

stages:
  - name: shellcheck build.sh
    if: type = pull_request
  - name: test
    if: type = pull_request
  - name: build
