os: linux
dist: focal
arch: amd64
language: shell

jobs:
  include:
    - stage: test
      language: rust
      rust: stable
      # ref: https://docs.travis-ci.com/user/languages/rust/#dependency-management
      cache: cargo
      before_script:
        - cd src/rust/receiver-mock/
      script:
        - cargo test

    - stage: build
      language: ruby
      services: docker
      script:
        - bash ci/build.sh
