#!/usr/bin/env bash

function print_help() {
  echo "K8S template generator"
}

function echo_stderr() {
  echo ${1} >&2
}

readonly arg=${1}

if [[ "${arg}" == "--help" ]]; then
  print_help
  exit 0
fi

readonly REPO_PATH="${REPO_PATH:-sumologic/sumologic}"
readonly REPO_URL="${REPO_URL:-https://sumologic.github.io/sumologic-kubernetes-collection}"

# Take data from stdin if available and put into tmpfile
tmpfile="$(mktemp /tmp/values.yaml.XXXXXX)"
extra_params=''
if [ ! read -t 0 ]; then
  cat <&0 > "${tmpfile}"
  extra_params="-f${tmpfile}"
fi

echo_stderr '# Add sumologic repository'
helm repo add sumologic "${REPO_URL}" 1>/dev/null 2>&1
echo_stderr '# Update repository'
helm repo update 1>/dev/null 2>&1
echo_stderr '# Generating template'
helm template "${REPO_PATH}" ${extra_params} "$@" 2>&1 | grep -vE '^manifest_sorter.go'
rm "${tmpfile}"
