#!/usr/bin/env bash

function print_help() {
  echo "K8S template generator"
}

function echoerr() {
  echo "${1}" >&2
}

readonly arg=${1}

if [[ "${arg}" == "--help" ]]; then
  print_help
  exit 0
fi

readonly REPO_PATH="${REPO_PATH:-sumologic/sumologic}"
readonly REPO_URL="${REPO_URL:-https://sumologic.github.io/sumologic-kubernetes-collection}"
readonly STDIN_WAIT_S="${STDIN_WAIT_S:-10}"

echoerr '# Add sumologic repository'
helm repo add sumologic "${REPO_URL}" 1>/dev/null 2>&1
echoerr '# Update repository'
helm repo update 1>/dev/null 2>&1

# Take data from stdin if available and put into tmpfile
tmpfile="$(mktemp /tmp/values.yaml.XXXXXX)"
extra_params=''
# Kubectl can take some time before stdin is available for reading
# thats why we check if just before it's required
if read -t "${STDIN_WAIT_S}" REPLY; then
  # Save first line read from stdin
  echo "${REPLY}" > "${tmpfile}"
  # Save rest of the stdin
  cat <&0 >> "${tmpfile}"
  extra_params="-f${tmpfile}"
fi

echoerr '# Generating template'
helm template "${REPO_PATH}" ${extra_params} "$@" 2>&1 | grep -vE '^manifest_sorter.go'
rm "${tmpfile}"
