#!/usr/bin/env bash

key="${1}"
shift

echo '# Add sumologic repository'
helm repo add sumologic https://sumologic.github.io/sumologic-kubernetes-collection 1>/dev/null 2>&1
echo '# Update repository'
helm repo update 1>/dev/null 2>&1
echo "# Generating override for ${key}"
helm show values $@ sumologic/sumologic | yq r - "${key}"
