#!/usr/bin/env bash

function print_help() {
  echo "Generate kubernetes yaml file values with a designated key's override"
}

readonly arg=${1}

if [[ "${arg}" == "--help" ]]; then
  print_help
  exit 0
fi

readonly REPO_PATH="${REPO_PATH:-sumologic/sumologic}"
readonly REPO_URL="${REPO_URL:-https://sumologic.github.io/sumologic-kubernetes-collection}"

key="${1}"
shift

echo '# Add sumologic repository'
helm repo add sumologic "${REPO_URL}" 1>/dev/null 2>&1
echo '# Update repository'
helm repo update 1>/dev/null 2>&1
echo "# Generating override for ${key}"
helm show values "$@" "${REPO_PATH}" | yq r - "${key}"
