[package]
name = "receiver-mock"
version = "0.1.0"
authors = ["Dominik Rosiek <drosiek@sumologic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^3"
actix-http = "^2"
actix-service = "^1.0"
actix-rt = "^1"
bytes = "0.5"
serde = "1.0.106"
serde_derive = "1"
clap = "2.33.1"
timer = "0.2"
futures = "^0.3"
futures-util = "^0.3"
chrono = "^0.4"
json_str = "*"
derive_more = "^0.99.11"
rand = "^0.7"
