[package]
name = "receiver-mock"
version = "0.1.0"
authors = ["Dominik Rosiek <drosiek@sumologic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.1"
actix-web = "3"
actix-http = "2"
bytes = "0.5"
futures-util = "0.2"
serde = "1.0.106"
serde_json = "1.0"
serde_derive = "1"
clap = "2.33.1"
flate2 = "1.0"
timer = "0.2"
chrono = "^0.4"
