[package]
name = "receiver-mock"
version = "0.1.0"
authors = ["Dominik Rosiek <drosiek@sumologic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
hyper = "0.13"
hyper-router = "^0.5"
futures-util = "0.2"
serde = "1.0.106"
serde_json = "1.0"
clap = "2.33.1"
flate2 = "1.0"