[package]
name = "receiver-mock"
version = "0.1.0"
authors = ["Sumo Logic <collection@sumologic.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^3"
actix-http = "~2.1.0"
actix-service = "^1.0"
actix-rt = "^2"
bytes = "^0.5.6"
serde = "1.0.131"
serde_derive = "1"
clap = "2.34.0"
timer = "0.2"
futures = "^0.3"
futures-util = "^0.3"
chrono = { version = "^0.4", features = ["serde"] }
json_str = "*"
rand = "^0.8"
prometheus-parse = { git = "https://github.com/ccakes/prometheus-parse-rs", rev = "a4574e9bade29b8af31e68b68a5392c61cbb74cd" }
