[package]
name = "receiver-mock"
version = "0.1.0"
authors = ["Sumo Logic <collection@sumologic.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
actix-http = "3.2.2"
actix-service = "1"
actix-rt = "2"
anyhow = "1.0.63"
bytes = "1"
base64 = "0.13"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
clap = "2.34.0"
timer = "0.2"
chrono = { version = "0.4", features = ["serde"] }
json_str = "*"
rand = "0.8"
prometheus-parse = { git = "https://github.com/ccakes/prometheus-parse-rs", rev = "a4574e9bade29b8af31e68b68a5392c61cbb74cd" }
http = "0.2"
opentelemetry-proto = { git = "https://github.com/open-telemetry/opentelemetry-rust", features = ["gen-tonic", "build-server", "logs", "metrics", "traces"] }
prost = "0.10.4"
itertools = "0.10.3"
log = "0.4.17"
simple_logger = "2.3.0"
hex = "0.4.3"
