---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-cleaner
  namespace: sumologic

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pvc-cleaner
  namespace: sumologic
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pvc-cleaner
  namespace: sumologic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pvc-cleaner
subjects:
- kind: ServiceAccount
  name: pvc-cleaner
  namespace: sumologic
