name: Build and push docker images

on:
  workflow_call:
    inputs:
      build_tag:
        description: Docker tag for the built image
        required: true
        type: string
      push_cache:
        description: Should the build cache be pushed to the repository?
        default: false
        required: false
        type: boolean
      tag_latest:
        description: Should the image be tagged with "latest" in addition to the build tag
        default: false
        required: false
        type: boolean
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true


jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Build kubernetes-tools image
        run: make build-image BUILD_TAG=${{ inputs.build_tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push kubernetes-tools image to Docker Hub
        run: make push-image BUILD_TAG=${{ inputs.build_tag }}
      - name: Push kubernetes-tools image build cache to Docker Hub
        if: ${{ inputs.push_cache }}
        run: make push-image-cache BUILD_TAG=${{ inputs.build_tag }}
      - name: Tag latest to point to most recent release in Docker Hub
        if: ${{ inputs.tag_latest }}
        run: make tag-release-image-with-latest BUILD_TAG=${{ inputs.build_tag }}
      - name: Login to ECR
        run: make login-ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push image to ECR
        run: make push-image-ecr BUILD_TAG=${{ inputs.build_tag }}
      - name: Push kubernetes-tools image build cache to ECR
        if: ${{ inputs.push_cache }}
        run: make push-image-cache-ecr BUILD_TAG=${{ inputs.build_tag }}
      - name: Tag latest to point to most recent release in ECR
        if: ${{ inputs.tag_latest }}
        run: make tag-release-image-with-latest-ecr BUILD_TAG=${{ inputs.build_tag }}
