name: Build binaries

on:
  workflow_call:

jobs:
  build-binaries:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Build
        run: make build-update-collection-v3
      - name: List
        run: ls
        working-directory: ./src/go/cmd/update-collection-v3
      - name: Store binary as action artifact
        uses: actions/upload-artifact@v3
        with:
          name: collection-sumo-windows_arm64
          path: ./src/go/cmd/update-collection-v3/collection-sumo-windows_arm64
          if-no-files-found: error
      - name: Store binary as action artifact
        uses: actions/upload-artifact@v3
        with:
          name: collection-sumo-windows_amd64
          path: ./src/go/cmd/update-collection-v3/collection-sumo-windows_amd64
          if-no-files-found: error
      - name: Store binary as action artifact
        uses: actions/upload-artifact@v3
        with:
          name: collection-sumo-linux_amd64
          path: ./src/go/cmd/update-collection-v3/collection-sumo-linux_amd64
          if-no-files-found: error
      - name: Store binary as action artifact
        uses: actions/upload-artifact@v3
        with:
          name: collection-sumo-linux_arm64
          path: ./src/go/cmd/update-collection-v3/collection-sumo-linux_arm64
          if-no-files-found: error
      - name: Store binary as action artifact
        uses: actions/upload-artifact@v3
        with:
          name: collection-sumo-darwin_amd64
          path: ./src/go/cmd/update-collection-v3/collection-sumo-darwin_amd64
          if-no-files-found: error
      - name: Store binary as action artifact
        uses: actions/upload-artifact@v3
        with:
          name: collection-sumo-darwin_arm64
          path: ./src/go/cmd/update-collection-v3/collection-sumo-darwin_arm64
          if-no-files-found: error