name: Dev builds

on:
  push:
    branches:
      - main
      - 'release-v[0-9]+.[0-9]+'
      - 'rnishtala-migration-tool-binaries'

jobs:
  extract-image-tag:
    runs-on: ubuntu-20.04
    outputs:
      build_tag: ${{ steps.extract_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Unshallow git repo
        run: git fetch -v --tags --unshallow origin "$(git rev-parse --abbrev-ref HEAD)"
      - name: Extract tag
        id: extract_tag
        run: |
          tag=$(git describe --tags)
          echo "::set-output name=tag::$(echo ${tag#v})"
      - name: Print tag
        run: echo "Running dev build for ${{ steps.extract_tag.outputs.tag }}"
  build-and-push-image:
    uses: SumoLogic/sumologic-kubernetes-tools/.github/workflows/build_and_push_image.yml@main
    needs: extract-image-tag
    with:
      build_tag: ${{ needs.extract-image-tag.outputs.build_tag }}
      push_cache: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  buils-binaries:
    uses: SumoLogic/sumologic-kubernetes-tools/.github/workflows/build_binaries.yml


