name: Dev builds

on:
  push:
    branches:
      - main
      - 'release-v[0-9]+.[0-9]+'

jobs:
  extract-image-tag:
    runs-on: ubuntu-20.04
    outputs:
      build_tag: ${{ steps.extract_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Unshallow git repo
        run: git fetch -v --tags --unshallow origin "$(git rev-parse --abbrev-ref HEAD)"
      - name: Extract tag
        id: extract_tag
        run: |
          tag=$(git describe --tags)
          echo "tag=$(echo ${tag#v})" >> $GITHUB_OUTPUT
      - name: Print tag
        run: echo "Running dev build for ${{ steps.extract_tag.outputs.tag }}"
  build-and-push-image:
    uses: ./.github/workflows/build_and_push_image.yml
    needs: extract-image-tag
    with:
      build_tag: ${{ needs.extract-image-tag.outputs.build_tag }}
      push_cache: true
      suffix: tools
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  build-and-push-image-kubectl:
    uses: ./.github/workflows/build_and_push_image.yml
    needs: extract-image-tag
    with:
      build_tag: ${{ needs.extract-image-tag.outputs.build_tag }}
      suffix: kubectl
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_LOGIN_KUBECTL }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_KUBECTL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_KUBECTL }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_KUBECTL }}
  build-and-push-image-sumologic-mock:
    uses: ./.github/workflows/build_and_push_image.yml
    needs: extract-image-tag
    with:
      build_tag: ${{ needs.extract-image-tag.outputs.build_tag }}
      suffix: sumologic-mock
      push_cache: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_LOGIN_SUMOLOGIC_MOCK }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD_SUMOLOGIC_MOCK }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SUMOLOGIC_MOCK }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SUMOLOGIC_MOCK }}
  build-binaries:
    uses: ./.github/workflows/build_binaries.yml
