name: Dev builds

on:
  push:
    branches:
      - main
      - 'release-v[0-9]+.[0-9]+'

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Unshallow git repo
        run: git fetch -v --tags --unshallow origin "$(git rev-parse --abbrev-ref HEAD)"
      - name: Extract tag
        id: extract_tag
        run: |
          tag=$(git describe --tags)
          echo "::set-output name=tag::$(echo ${tag#v})"
      - name: Print tag
        run: echo "Running dev build for ${{ steps.extract_tag.outputs.tag }}"
      - name: Build kubernetes-tools image
        run: make build-release-image BUILD_TAG=${{ steps.extract_tag.outputs.tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push kubernetes-tools image to Docker Hub
        run: make push-image BUILD_TAG=${{ steps.extract_tag.outputs.tag }}
      - name: Push kubernetes-tools image build cache to Docker Hub
        run: make push-image-cache BUILD_TAG=${{ steps.extract_tag.outputs.tag }}
      - name: Login to ECR
        run: make login-ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push image to ECR
        run: make push-image-ecr BUILD_TAG=${{ steps.extract_tag.outputs.tag }}
      - name: Push kubernetes-tools image build cache to ECR
        run: make push-image-cache-ecr BUILD_TAG=${{ steps.extract_tag.outputs.tag }}
