name: Pre release builds

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/v})"
      - name: Print tag
        run: echo "Running pre release build for ${{ steps.extract_tag.outputs.tag }}"
      - name: Build kubernetes-tools image
        run: make build-image BUILD_TAG=${{ steps.extract_tag.outputs.tag }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push kubernetes-tools image
        run: make push-image BUILD_TAG=${{ steps.extract_tag.outputs.tag }}
