name: Pre release builds

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  extract-image-tag:
    runs-on: ubuntu-20.04
    outputs:
      build_tag: ${{ steps.extract_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/v})"
      - name: Print tag
        run: echo "Running pre release build for ${{ steps.extract_tag.outputs.tag }}"
  build-and-push-image:
    uses: SumoLogic/sumologic-kubernetes-tools/.github/workflows/build_and_push_image.yml@main
    needs: extract-image-tag
    with:
      build_tag: ${{ needs.extract-image-tag.outputs.build_tag }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
