name: PRs checks

on:
  pull_request:
    branches:
      - main
      - 'release-v[0-9]+.[0-9]+'

jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1.1.3
      - name: Install markdownlint
        run: gem install mdl
      - name: Check markdown files with markdownlint
        run: make markdownlint

  test-sumologic-mock:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Build Sumo Logic Mock
        working-directory: src/rust/sumologic-mock/
        run: cargo rustc -- -D warnings
      - name: Check sumologic-mock formatting
        working-directory: src/rust/sumologic-mock/
        run: make check-rustfmt
      - name: Test sumologic-mock
        working-directory: src/rust/sumologic-mock/
        run: make test

  build-image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build kubernetes-tools image
        run: make build-image
      - name: Test kubernetes-tools image
        run: make test-image

  test-update-collection-v3:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build update-collection-v3
        run: make build-update-collection-v3
      - name: Test update-collection-v3
        run: make test-update-collection-v3
