name: Release builds

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  extract-image-tag:
    runs-on: ubuntu-20.04
    outputs:
      build_tag: ${{ steps.extract_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/v})"
      - name: Print tag
        run: echo "Running release build for ${{ steps.extract_tag.outputs.tag }}"
  build-and-push-image:
    uses: ./.github/workflows/build_and_push_image.yml
    needs: extract-image-tag
    with:
      build_tag: ${{ needs.extract-image-tag.outputs.build_tag }}
      tag_latest: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SUFFIX: tools
  build-and-push-image-kubectl:
    uses: ./.github/workflows/build_and_push_image.yml
    needs: extract-image-tag
    with:
      build_tag: ${{ needs.extract-image-tag.outputs.build_tag }}
      tag_latest: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_KUBECTL }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_KUBECTL }}
      SUFFIX: kubectl
  build-binaries:
    uses: ./.github/workflows/build_binaries.yml
  create-release:
    name: Create Github release
    runs-on: ubuntu-20.04
    needs:
      - build-binaries
      - extract-image-tag
    steps:
      - name: Print tag
        run: echo "v${{ needs.extract-image-tag.outputs.build_tag }}"
      - name: Download all binaries stored as artifact
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          body: |
            ## v${{ needs.extract-image-tag.outputs.build_tag }}
          artifacts: "artifacts/*/*"
          artifactErrorsFailBuild: true
          replacesArtifacts: true
